[build]
  publish = "dist"
  command = "npm run build:netlify"

[functions]
  directory = "api"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[template.environment]
  ABLY_API_KEY = "change me to your Ably API key"
  GITHUB_WEBHOOK_SECRET = "change me to your GitHub webhook secret"
